services:
  postgres:
    image: postgres:14
    container_name: rural_producers_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rural_producers
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rural_network

volumes: # Certifique-se de incluir esta seção
  postgres_data:

networks:
  rural_network:

